name: Test project

on:
  push:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Display my first "Hello, world!"
    - run: echo Hello, world!